<!DOCTYPE html>
<html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Kasir · {{ auth()->user()->tenant->name }} — GrowPOS</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
@php
    $catalog = $products->map(fn($p) => [
        'id'=>$p->id, 'name'=>$p->product_name, 'sku'=>$p->sku, 'barcode'=>$p->barcode, 'type'=>$p->type, 'category_id'=>$p->category_id,
        'price'=>(int)$p->sell_price, 'discount'=>(int)$p->discount_applied, 'stock'=>(int)$p->stock,
        'tracked'=>$p->type === 'product' && $p->manage_stock, 'image'=>$p->image ? asset('storage/'.$p->image) : null,
        'variants'=>$p->variants->map(fn($v)=>['id'=>$v->id,'name'=>$v->name,'price'=>(int)round($v->price),'discount'=>(int)$v->discount,'stock'=>(int)$v->stock])->values(),
        'addons'=>$p->addons->map(fn($a)=>['id'=>$a->id,'name'=>$a->name,'price'=>(int)$a->price])->values(),
    ])->values();
    $posConfig = ['food'=>auth()->user()->tenant->hasBusinessModule('food'),'pendingPayments'=>$pendingPayments,'tenant'=>auth()->user()->tenant_id,'user'=>auth()->id(),'csrf'=>csrf_token(),'checkout'=>route('pos.store', absolute:false),'products'=>$catalog,'shift'=>$activeShift,'taxRate'=>($settings['tax_active']??'0')==='1' ? min(100,max(0,(float)($settings['tax_percentage']??0))) : 0];
@endphp
<body class="gp-terminal" x-data="growPos">
<script type="application/json" id="grow-pos-data">@json($posConfig)</script>
<header class="gp-terminal-header" :inert="!!modal"><div class="gp-row"><a href="{{ route('dashboard') }}" class="gp-step-number" aria-label="Ringkasan usaha">G</a><div><div class="font-bold text-sm">{{ auth()->user()->tenant->name }}</div><div class="gp-muted" style="font-size:11px">{{ auth()->user()->name }} <span aria-live="polite" :class="online ? 'gp-status' : 'text-amber-700'" x-text="online ? '· Terhubung' : '· Offline'"></span></div></div></div>
<div class="gp-row">@if(auth()->user()->tenant->hasBusinessModule('services'))<a class="gp-btn" href="{{ route('services.index') }}">Pengerjaan jasa</a>@endif<button class="gp-btn" x-show="pendingPayments.length" @click="modal='pendingPayments'">QRIS menunggu <span x-text="pendingPayments.length"></span></button>@if(auth()->user()->tenant->hasBusinessModule('food'))<a href="{{ route('kitchen.index') }}" class="gp-btn gp-hide-mobile">Dapur ↗</a>@endif<button class="gp-btn" @click="modal='queue'">Antrean <span class="gp-chip" x-text="queue.length">0</span></button><button class="gp-btn" @click="shift ? prepareClose() : (modal='openShift')" x-text="shift ? 'Tutup shift' : 'Buka shift'"></button><a href="{{ route('help') }}" class="gp-btn" aria-label="Panduan">?</a></div></header>
<div class="mx-4 mt-4 gp-alert" x-show="!online" x-cloak>Offline. Transaksi tunai disimpan di perangkat ini dan diperiksa server saat tersambung kembali. QRIS membutuhkan koneksi.</div>
<div class="mx-4 mt-4 gp-alert" x-show="notice" x-cloak role="status"><span x-text="notice"></span><button class="float-right ml-4" @click="notice=''" aria-label="Tutup pemberitahuan">×</button></div>
<div class="mx-4 mt-4 gp-alert gp-error" x-show="error" x-cloak role="alert"><span x-text="error"></span><button class="float-right ml-4" @click="error=''" aria-label="Tutup kesalahan">×</button></div>
<main class="gp-terminal-grid" :inert="!!modal">
<section><div class="gp-row gp-between mb-4"><div><div class="gp-eyebrow">TERMINAL KASIR</div><h1 class="gp-title" style="font-size:27px">Ada pesanan apa?</h1></div><button class="gp-btn" @click="modal='drafts'">Pesanan tersimpan <span x-text="drafts.length" class="gp-chip"></span></button></div>
<label class="gp-field"><span class="sr-only">Cari produk, layanan, atau barcode</span><input x-model.debounce.120ms="search" @keydown.enter.prevent="scan($event.target.value)" type="search" placeholder="Cari produk, layanan, atau barcode…" aria-label="Cari produk, layanan, atau barcode" style="margin:0;background:white"></label>
<div class="gp-scroll-tabs"><button class="gp-btn" :class="category==='all' && 'gp-primary'" @click="category='all'">Semua item</button><button class="gp-btn" :class="category==='favorites' && 'gp-primary'" @click="category='favorites'">★ Favorit</button>@foreach($categories as $category)<button class="gp-btn" :class="Number(category)==={{ $category->id }} && 'gp-primary'" @click="category='{{ $category->id }}'">{{ $category->name }}</button>@endforeach</div>
<div class="gp-row mb-3"><label class="gp-field">Tampilkan<select x-model="itemType"><option value="all">Barang & jasa</option><option value="product">Barang</option><option value="service">Jasa / layanan</option></select></label></div>
<div class="gp-menu-grid"><template x-for="p in filtered" :key="p.id"><article class="gp-product"><button class="gp-favorite" @click="favorite(p.id)" :aria-label="(favorites.includes(p.id)?'Hapus favorit ':'Jadikan favorit ')+p.name" :aria-pressed="favorites.includes(p.id)" x-text="favorites.includes(p.id)?'★':'☆'"></button><button class="gp-product-main" @click="choose(p)"><div class="gp-product-visual"><template x-if="p.image"><img :src="p.image" alt="" loading="lazy"></template><span x-show="!p.image" x-text="p.name.slice(0,2).toUpperCase()"></span></div><div class="font-semibold text-sm" x-text="p.name"></div><div class="gp-row gp-between mt-2"><strong class="text-sm" style="color:#17694d" x-text="money(p.price-p.discount)"></strong><span class="gp-muted" style="font-size:10px" x-text="p.variants.length ? 'Pilihan varian' : (p.type==='service' ? 'Jasa · tanpa stok' : (p.tracked ? 'Stok '+p.stock : 'Tersedia'))"></span></div></button></article></template></div>
<div x-show="!filtered.length" class="gp-empty gp-card mt-4"><p>Tidak ada menu yang cocok.</p>@if(auth()->user()->role==='admin')<a class="gp-btn mt-4" href="{{ route('getting-started') }}">Siapkan atau impor menu →</a>@endif</div>
</section>
<aside class="gp-card gp-cart" id="order-cart"><div class="gp-row gp-between"><h2 class="font-bold text-lg">Pesanan sekarang</h2><span class="gp-chip" x-text="itemCount+' item'"></span></div><div class="gp-grid mt-4" style="grid-template-columns:1fr 1fr;gap:10px"><label class="gp-field">Jenis pesanan<select x-model="orderType"><option value="takeaway">Langsung / ambil sendiri</option>@if(auth()->user()->tenant->hasBusinessModule('food'))<option value="dine_in">Makan di tempat</option>@endif<option value="delivery">Diantar</option></select></label><label class="gp-field" x-show="orderType==='dine_in'">Nomor meja<input x-model="table" maxlength="30" placeholder="Mis. 04"></label></div>
<div class="gp-empty" x-show="!cart.length"><div class="gp-step-number mx-auto mb-3">＋</div>Pilih produk atau layanan untuk memulai.<br><span class="gp-muted">Pilihan dan catatan bisa ditambahkan.</span></div>
<template x-for="line in cart" :key="line.key"><div class="gp-cart-line"><div class="gp-row gp-between"><strong class="text-sm" x-text="line.name"></strong><span class="text-sm" x-text="money((line.price-line.discount)*line.quantity)"></span></div><div class="gp-muted" x-show="line.addons.length" x-text="line.addons.join(', ')"></div><div class="gp-muted" x-show="line.note" x-text="line.note"></div><div class="gp-row gp-between mt-2"><span class="gp-muted" x-text="money(line.price-line.discount)+' / item'"></span><div class="gp-quantity"><button @click="quantity(line.key,-1)" :aria-label="'Kurangi '+line.name">−</button><span x-text="line.quantity"></span><button @click="quantity(line.key,1)" :aria-label="'Tambah '+line.name">+</button></div></div></div></template>
@can('feature-crm')<label class="gp-field mt-4">Pelanggan / member<select x-model="customer"><option value="">Pelanggan umum</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}{{ $customer->is_member ? ' · Member' : '' }}</option>@endforeach</select></label>@endcan
<label class="gp-field mt-4">Catatan pesanan<input x-model="orderNote" placeholder="Mis. bungkus terpisah" maxlength="300"></label>
<div class="gp-list mt-4 text-sm"><div class="gp-row gp-between"><span class="gp-muted">Subtotal</span><span x-text="money(amounts.subtotal)"></span></div><div class="gp-row gp-between" x-show="amounts.discount"><span class="gp-muted">Diskon menu</span><span x-text="'-'+money(amounts.discount)"></span></div><div class="gp-row gp-between" x-show="amounts.tax"><span class="gp-muted">Pajak</span><span x-text="money(amounts.tax)"></span></div><div class="gp-row gp-between"><strong>Total</strong><strong class="text-xl" x-text="money(amounts.total)"></strong></div></div>
<button class="gp-btn gp-primary w-full mt-3" @click="pay()" :disabled="!cart.length || busy">Lanjut pembayaran →</button><button class="gp-btn w-full mt-2" @click="hold()" :disabled="!cart.length">Simpan pesanan sementara</button><p class="gp-muted text-center mt-3" style="font-size:10px">Draft disimpan pada perangkat ini.</p></aside>
</main>
<button class="gp-btn gp-primary gp-mobile-cart gp-between" :inert="!!modal" @click="document.getElementById('order-cart').scrollIntoView({behavior:'smooth'})"><span x-text="itemCount+' item · Lihat pesanan'"></span><strong x-text="money(amounts.total)"></strong></button>
<div class="gp-dialog" x-show="modal" x-cloak @keydown.escape.window="if(!busy)modal=''" @keydown.tab="trapFocus($event)" role="dialog" aria-modal="true" aria-label="Detail kasir"><div class="gp-dialog-panel"><button class="gp-btn float-right" @click="modal=''" :disabled="busy" aria-label="Tutup dialog">×</button>
<p class="gp-alert gp-error mb-3 clear-both" x-show="error" x-text="error" role="alert"></p>
<template x-if="modal==='item' && selected"><section><h2 x-text="selected.name"></h2><p class="gp-muted mt-2">Sesuaikan pilihan pesanan.</p><label class="gp-field mt-5" x-show="selected.variants.length">Ukuran / varian<select x-model="variant"><option value="">Reguler</option><template x-for="v in selected.variants" :key="v.id"><option :value="v.id" x-text="v.name+' · '+money(v.price-v.discount)"></option></template></select></label><div class="mt-4"><template x-for="a in selected.addons" :key="a.id"><label class="gp-row py-3 border-b text-sm"><input type="checkbox" :value="a.id" x-model.number="addonIds"><span x-text="a.name" class="flex-1"></span><span x-text="'+'+money(a.price)"></span></label></template></div><label class="gp-field mt-4">Catatan item<input x-model="itemNote" maxlength="300" placeholder="Mis. less ice, tanpa gula"></label><button class="gp-btn gp-primary w-full mt-5" @click="addItem()">Tambahkan · <span x-text="money(selectedUnit.price-selectedUnit.discount)"></span></button></section></template>
<section x-show="modal==='pay'"><h2>Pembayaran</h2><p class="gp-metric" x-text="money(amounts.total)"></p><div class="gp-row mt-4"><button class="gp-btn" :class="method==='cash' && 'gp-primary'" @click="method='cash'">Tunai</button>@can('feature-qris')<button class="gp-btn" :class="method==='midtrans' && 'gp-primary'" @click="method='midtrans'" :disabled="!online">QRIS</button>@endcan</div><form @submit.prevent="submit()"><div x-show="method==='cash'"><label class="gp-field mt-5">Uang diterima (Rp)<input type="number" x-model="cash" min="0" inputmode="numeric" :required="method==='cash'"></label><div class="gp-row mt-3"><button type="button" class="gp-btn" @click="cash=amounts.total">Uang pas</button><template x-for="amount in [20000,50000,100000]" :key="amount"><button type="button" class="gp-btn" x-show="amount>=amounts.total" @click="cash=amount" x-text="money(amount)"></button></template></div><p class="gp-muted mt-4">Kembalian <strong x-text="money(Math.max(0,Number(cash)-amounts.total))"></strong></p></div><p class="gp-muted mt-4" x-show="method==='midtrans'">Buat QR, lalu tunggu konfirmasi pembayaran dari server.</p><button class="gp-btn gp-primary w-full mt-5" :disabled="busy" x-text="busy?'Memproses…':(!online?'Simpan transaksi tunai di perangkat':'Konfirmasi pembayaran')"></button></form></section>
<section x-show="modal==='drafts'"><h2>Pesanan tersimpan</h2><p class="gp-muted mt-2">Belum dibayar dan belum memotong stok.</p><template x-for="draft in drafts" :key="draft.id"><button class="gp-btn gp-between w-full mt-3" @click="resume(draft.id)"><span x-text="draft.name"></span><span>Buka →</span></button></template><p class="gp-empty" x-show="!drafts.length">Belum ada draft pesanan.</p></section>
<section x-show="modal==='queue'"><h2>Antrean perangkat</h2><p class="gp-muted mt-2">Transaksi di sini belum terkonfirmasi tersimpan di server. Jangan menerima pembayaran kedua kali.</p><div class="gp-row mt-4"><button class="gp-btn" @click="syncQueue()" :disabled="syncing || busy || !online" x-text="syncing?'Menyinkronkan…':'Coba sinkronkan tunai'"></button><button class="gp-btn" @click="backupQueue()" :disabled="!queue.length">Unduh cadangan</button></div><template x-for="entry in queue" :key="entry.payload.checkout_key"><div class="gp-card mt-4"><strong x-text="money(entry.payload.grand_total)"></strong><p class="gp-muted" x-text="entry.payload.payment_method+' · '+new Date(entry.payload.sold_at).toLocaleString('id-ID')"></p><p class="gp-muted break-all" style="font-size:10px" x-text="entry.payload.checkout_key"></p><p class="gp-alert mt-3" x-show="entry.error" x-text="entry.error"></p><button class="gp-btn mt-3" @click="retry(entry)" :disabled="!online || busy || syncing">Periksa / kirim ulang</button></div></template><p class="gp-empty" x-show="!queue.length">✓ Semua transaksi sudah tersinkron.</p><a class="gp-btn mt-4" href="{{ route('help') }}">Cara menangani antrean tertahan</a></section>
<section x-show="modal==='pendingPayments'"><h2>QRIS menunggu konfirmasi</h2><p class="gp-muted mt-2">Buka kembali pembayaran yang sudah dibuat. Periksa status sebelum menerima pembayaran lain.</p><template x-for="pending in pendingPayments" :key="pending.order_id"><div class="gp-card mt-3"><p class="break-all" x-text="pending.invoice_number"></p><strong x-text="money(pending.grand_total)"></strong><button class="gp-btn mt-3" @click="payment=pending;modal='qris';checkPayment()">Buka dan periksa</button></div></template></section>
<template x-if="modal==='qris' && payment"><section><h2>Scan untuk membayar</h2><p class="gp-metric" x-text="money(payment.grand_total)"></p><img :src="payment.qr_url" alt="Kode QRIS pembayaran" class="w-64 h-64 object-contain mx-auto"><p class="gp-muted mt-3">Tunggu konfirmasi server. QR ini dapat dibuka kembali melalui tombol QRIS menunggu.</p><button class="gp-btn gp-primary w-full mt-4" @click="checkPayment()" :disabled="busy" x-text="busy?'Memeriksa…':'Periksa pembayaran'"></button></section></template>
<template x-if="modal==='receipt' && receipt"><section><span class="gp-chip">TERCATAT DI SERVER</span><h2 class="mt-3">Transaksi berhasil.</h2><p class="gp-metric" x-text="money(receipt.grand_total)"></p><p class="gp-muted break-all" x-text="receipt.invoice_number"></p><a class="gp-btn gp-primary w-full mt-5" :href="'/orders/'+receipt.order_id+'/print'" target="_blank" rel="noopener">Cetak struk ↗</a><button class="gp-btn w-full mt-2" @click="location.reload()">Pesanan berikutnya</button></section></template>
<section x-show="modal==='openShift'"><h2>Siap buka kedai?</h2><p class="gp-muted mt-2">Catat modal tunai yang ada di laci sebelum transaksi pertama.</p><form @submit.prevent="openShift()"><label class="gp-field mt-5">Modal awal (Rp)<input type="number" x-model="shiftCash" min="0" required></label><button class="gp-btn gp-primary w-full mt-5" :disabled="busy">Buka shift</button></form></section>
<section x-show="modal==='closeShift'"><h2>Tutup shift</h2><p class="gp-muted mt-2">Pastikan antrean di perangkat lain juga sudah tersinkron.</p><p class="gp-muted mt-5">Kas yang diharapkan</p><p class="gp-metric" x-text="money(shiftSummary?.cash_expected)"></p><form @submit.prevent="closeShift()"><label class="gp-field">Uang fisik di laci (Rp)<input type="number" min="0" x-model="shiftCash" required></label><button class="gp-btn gp-primary w-full mt-5" :disabled="busy">Simpan & tutup shift</button></form></section>
</div></div>
</body></html>
