<x-app-layout>
@section('title', 'Mulai berjualan')
@php($tenant = auth()->user()->tenant)
<div class="[max-width:1280px] [margin:auto] p-7 [color:#18372d] max-[701px]:[padding:20px_16px]">
    <div class="[font-size:11px] font-bold [letter-spacing:0.14em] uppercase [color:#647c72]">SELAMAT DATANG DI GROWPOS</div>
    <h1 class="[font-size:clamp(24px,_3vw,_34px)] font-bold [letter-spacing:-0.04em] [line-height:1.2] [margin:8px_0]">Dari katalog pertama,<br>ke pelanggan pertama.</h1>
    <p class="[color:#65796f] [font-size:13px] [line-height:1.6]">Siapkan {{ $tenant->name }} sesuai kebutuhan {{ \App\Support\BusinessProfile::TYPES[$tenant->businessType()] }}.</p>
    @if(auth()->user()->role === 'admin')<a class="inline-flex items-center justify-center gap-2 min-h-11 [padding:10px_17px] [border:1px_solid_#dae4dd] rounded-md bg-white [color:#234a3b] [font-size:13px] font-semibold cursor-pointer hover:[background:#f1f7f3] disabled:[opacity:0.45] disabled:cursor-wait focus-visible:[outline:3px_solid_#90b9a5] focus-visible:[outline-offset:3px] mt-4" href="{{ route('business.edit') }}">Atur jenis usaha & fitur</a>@endif
    @if(!$tenant->currentPlan())<div class="[padding:13px_16px] rounded-md [background:#fff6df] [color:#81591c] [font-size:13px] [line-height:1.6] mt-6">Pilih paket untuk mengaktifkan katalog dan transaksi. <a class="underline" href="{{ route('billing.index') }}">Lihat paket →</a></div>@endif
    <div class="grid [gap:18px] mt-6 [grid-template-columns:repeat(auto-fit,minmax(230px,1fr))]">
        @foreach([[$tenant->catalogLabel(), 'Tambahkan barang atau layanan beserta harga yang benar.', $hasMenu, route('products.create'), 'Isi katalog'], ['Buka shift', 'Catat modal tunai awal di laci kasir.', $hasShift, route('pos.index'), 'Buka kasir'], ['Transaksi pertama', 'Pilih barang atau jasa, terima pembayaran, lalu cetak struk.', $hasSale, route('pos.index'), 'Mulai transaksi']] as $step)
        <div class="bg-white [border:1px_solid_#e1e9e4] rounded-lg [padding:22px] [box-shadow:0_2px_5px_#17392c03] max-[701px]:[padding:18px] flex [gap:15px] [align-items:flex-start]"><div class="w-9 h-9 grid place-items-center rounded-full [background:#edf5ee] [color:#17694d] font-bold shrink-0">{{ $step[2] ? '✓' : $loop->iteration }}</div><div><h2 class="font-semibold">{{ $step[0] }}</h2><p class="[color:#65796f] [font-size:13px] [line-height:1.6] mt-2">{{ $step[1] }}</p><a class="inline-flex items-center justify-center gap-2 min-h-11 [padding:10px_17px] [border:1px_solid_#dae4dd] rounded-md bg-white [color:#234a3b] [font-size:13px] font-semibold cursor-pointer hover:[background:#f1f7f3] disabled:[opacity:0.45] disabled:cursor-wait focus-visible:[outline:3px_solid_#90b9a5] focus-visible:[outline-offset:3px] mt-4" href="{{ $step[3] }}">{{ $step[4] }} →</a></div></div>
        @endforeach
    </div>
    @if(auth()->user()->role === 'admin')
    <div class="grid [gap:18px] [grid-template-columns:1.5fr_1fr] max-[1001px]:[grid-template-columns:1fr] mt-6">
        <section class="bg-white [border:1px_solid_#e1e9e4] rounded-lg [padding:22px] [box-shadow:0_2px_5px_#17392c03] max-[701px]:[padding:18px]">
            <h2 class="font-semibold text-lg">Pindahkan katalog dalam satu file.</h2>
            <p class="[color:#65796f] [font-size:13px] [line-height:1.6] mt-2">Excel atau CSV, maksimal 500 baris. Kolom type: product untuk barang, service untuk jasa. Jasa tidak memotong stok. Template lama enam kolom tetap diterima sebagai barang.</p>
            <div class="flex gap-3 items-center flex-wrap mt-4"><a class="inline-flex items-center justify-center gap-2 min-h-11 [padding:10px_17px] [border:1px_solid_#dae4dd] rounded-md bg-white [color:#234a3b] [font-size:13px] font-semibold cursor-pointer hover:[background:#f1f7f3] disabled:[opacity:0.45] disabled:cursor-wait focus-visible:[outline:3px_solid_#90b9a5] focus-visible:[outline-offset:3px]" href="{{ route('menu.template') }}">Unduh template</a><a class="inline-flex items-center justify-center gap-2 min-h-11 [padding:10px_17px] [border:1px_solid_#dae4dd] rounded-md bg-white [color:#234a3b] [font-size:13px] font-semibold cursor-pointer hover:[background:#f1f7f3] disabled:[opacity:0.45] disabled:cursor-wait focus-visible:[outline:3px_solid_#90b9a5] focus-visible:[outline-offset:3px]" href="{{ route('menu.export') }}">Ekspor katalog</a></div>
            <form action="{{ route('getting-started.import') }}" method="post" enctype="multipart/form-data" class="mt-4">@csrf<label class="block [font-size:12px] font-semibold [color:#536b5e] [&_input]:block [&_input]:w-full [&_input]:[margin-top:7px] [&_input]:[border:1px_solid_#dce5de] [&_input]:[border-radius:9px] [&_input]:[padding:11px] [&_input]:bg-white [&_input]:[font-size:14px] [&_input]:[color:#18372d] [&_input]:min-h-11 [&_select]:block [&_select]:w-full [&_select]:[margin-top:7px] [&_select]:[border:1px_solid_#dce5de] [&_select]:[border-radius:9px] [&_select]:[padding:11px] [&_select]:bg-white [&_select]:[font-size:14px] [&_select]:[color:#18372d] [&_select]:min-h-11 [&_textarea]:block [&_textarea]:w-full [&_textarea]:[margin-top:7px] [&_textarea]:[border:1px_solid_#dce5de] [&_textarea]:[border-radius:9px] [&_textarea]:[padding:11px] [&_textarea]:bg-white [&_textarea]:[font-size:14px] [&_textarea]:[color:#18372d] [&_textarea]:min-h-11">File katalog<input type="file" name="file" accept=".xlsx,.csv" required></label><button class="inline-flex items-center justify-center gap-2 min-h-11 [padding:10px_17px] [border:1px_solid_#dae4dd] rounded-md bg-white [color:#234a3b] [font-size:13px] font-semibold cursor-pointer hover:[background:#f1f7f3] disabled:[opacity:0.45] disabled:cursor-wait focus-visible:[outline:3px_solid_#90b9a5] focus-visible:[outline-offset:3px] ![background:#17694d] !text-white ![border-color:#17694d] hover:![background:#12523d] mt-4">Impor katalog</button></form>
        </section>
        <section class="bg-white [border:1px_solid_#e1e9e4] rounded-lg [padding:22px] [box-shadow:0_2px_5px_#17392c03] max-[701px]:[padding:18px]">
            <h2 class="font-semibold text-lg">Contoh sesuai jenis usahamu</h2>
            <p class="[color:#65796f] [font-size:13px] [line-height:1.6] mt-2">{{ implode(', ', array_column(\App\Support\BusinessProfile::samples($tenant->businessType()), 'name')) }}. Contoh menjadi katalog sungguhan; sesuaikan harga, modal, dan stok sebelum menjual.</p>
            @if(!$hasMenu)<form method="post" action="{{ route('getting-started.sample') }}" class="mt-4">@csrf<button class="inline-flex items-center justify-center gap-2 min-h-11 [padding:10px_17px] [border:1px_solid_#dae4dd] rounded-md bg-white [color:#234a3b] [font-size:13px] font-semibold cursor-pointer hover:[background:#f1f7f3] disabled:[opacity:0.45] disabled:cursor-wait focus-visible:[outline:3px_solid_#90b9a5] focus-visible:[outline-offset:3px]">Tambahkan 4 contoh</button></form>@else<p class="inline-block [padding:5px_10px] rounded-full [background:#edf5ee] [color:#356649] [font-size:11px] font-semibold mt-4">Katalog sudah terisi</p>@endif
            <a class="inline-flex items-center justify-center gap-2 min-h-11 [padding:10px_17px] [border:1px_solid_#dae4dd] rounded-md bg-white [color:#234a3b] [font-size:13px] font-semibold cursor-pointer hover:[background:#f1f7f3] disabled:[opacity:0.45] disabled:cursor-wait focus-visible:[outline:3px_solid_#90b9a5] focus-visible:[outline-offset:3px] mt-4" href="{{ route('menu.configure') }}">{{ $tenant->hasBusinessModule('food') ? 'Varian, tambahan & resep' : 'Varian & pilihan' }} →</a>
        </section>
    </div>
    @endif
    <a class="inline-flex items-center justify-center gap-2 min-h-11 [padding:10px_17px] [border:1px_solid_#dae4dd] rounded-md bg-white [color:#234a3b] [font-size:13px] font-semibold cursor-pointer hover:[background:#f1f7f3] disabled:[opacity:0.45] disabled:cursor-wait focus-visible:[outline:3px_solid_#90b9a5] focus-visible:[outline-offset:3px] mt-6" href="{{ route('help') }}">Panduan operasional →</a>
</div>
</x-app-layout>
